services:
  app:
    image: ghcr.io/Chronote-Team/chronote
    container_name: chronote-test
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/config
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
